</div>

<div id="footer">
<div class="badges">
<a href="http://www.php.net"><img src="../../../dompdf/www/images/php5-power-micro.png" alt="php5 logo"/></a>
<a href="http://validator.w3.org"><img src="../../../dompdf/www/images/xhtml10.png" alt="valid xhtml"/></a>
<a href="http://jigsaw.w3.org/css-validator"><img src="../../../dompdf/www/images/css2.png" alt="valid css2"/></a>
</div>
</div>
</body> </html>
